# Generated by Django 4.0.4 on 2022-06-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodyAIpy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='AIResponse',
        ),
    ]
