# Generated by Django 4.0.4 on 2022-06-01 19:27

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moodyAIpy', '0002_rename_response_airesponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='init_date',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 1, 19, 27, 40, 106604, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
